<script setup lang="ts">
import { ref, computed } from 'vue'

// Reactive data
const selectedMonthRange = ref('all')
const selectedOffice = ref('all')

// Data from the original table
const officeData = ref({
  'Records Unit': [935, 897, 978, 894, 723, 848, 1120, 263, 1, 0, 0, 0],
  'ORED': [279, 258, 270, 219, 239, 248, 280, 74, 0, 0, 0, 0],
  'OARDMS': [363, 280, 312, 344, 313, 274, 398, 90, 0, 0, 0, 0],
  'OARDTS': [780, 784, 869, 699, 604, 760, 924, 223, 1, 0, 0, 0],
  'RSCIS': [32, 39, 35, 33, 34, 28, 56, 11, 0, 0, 0, 0]
})

const allMonths = ['Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun', 'Jul', 'Aug', 'Sep', 'Oct', 'Nov', 'Dec']
const officeNames = Object.keys(officeData.value)

// Computed properties
const currentDate = computed(() => {
  return new Date().toLocaleDateString('en-US', {
    year: 'numeric',
    month: 'long',
    day: 'numeric',
    hour: '2-digit',
    minute: '2-digit'
  })
})

const visibleMonths = computed(() => {
  return filterMonthsByRange(allMonths)
})

const filteredOffices = computed(() => {
  if (selectedOffice.value === 'all') {
    return officeNames
  }
  return [selectedOffice.value]
})

const monthlyTotals = computed(() => {
  const totals = []
  const monthIndices = getMonthIndices()
  
  for (const monthIndex of monthIndices) {
    let total = 0
    for (const office of filteredOffices.value) {
      total += officeData.value[office][monthIndex]
    }
    totals.push(total)
  }
  return totals
})

const grandTotal = computed(() => {
  return monthlyTotals.value.reduce((sum, total) => sum + total, 0)
})

// Methods
const filterMonthsByRange = (months: string[]) => {
  const currentMonth = new Date().getMonth() // 0-based index
  
  switch (selectedMonthRange.value) {
    case 'current-month':
      return [months[currentMonth]]
    
    case 'last-3-months':
      const last3Start = Math.max(0, currentMonth - 2)
      return months.slice(last3Start, currentMonth + 1)
    
    case 'last-6-months':
      const last6Start = Math.max(0, currentMonth - 5)
      return months.slice(last6Start, currentMonth + 1)
    
    case 'quarter-1':
      return months.slice(0, 3)
    
    case 'quarter-2':
      return months.slice(3, 6)
    
    case 'quarter-3':
      return months.slice(6, 9)
    
    case 'quarter-4':
      return months.slice(9, 12)
    
    case 'all':
    default:
      return months
  }
}

const getMonthIndices = () => {
  const visibleMonthNames = visibleMonths.value
  return visibleMonthNames.map(month => allMonths.indexOf(month))
}

const getOfficeData = (office: string) => {
  const monthIndices = getMonthIndices()
  return monthIndices.map(index => officeData.value[office][index])
}

const getOfficeTotal = (office: string) => {
  const data = getOfficeData(office)
  return data.reduce((sum, value) => sum + value, 0)
}

const getOfficeAverage = (office: string) => {
  const data = getOfficeData(office)
  const activeData = data.filter(value => value > 0) // Only count months with data
  if (activeData.length === 0) return '0'
  return Math.round(activeData.reduce((sum, value) => sum + value, 0) / activeData.length).toString()
}

const getPeakMonth = (office: string) => {
  const data = officeData.value[office]
  const maxValue = Math.max(...data)
  const maxIndex = data.indexOf(maxValue)
  return {
    month: allMonths[maxIndex],
    value: maxValue
  }
}
</script>

<template>
  <div class="text-white p-1 xs:p-2 sm:p-3 md:p-4 lg:p-6 xl:p-8 rounded-lg mb-2 sm:mb-3 md:mb-4">
    <div class="flex flex-col p-2 xs:p-3 sm:p-4 md:p-5 lg:p-6 xl:p-8">
      
      <div class="bg-white rounded-md sm:rounded-lg shadow-sm border p-2 xs:p-3 sm:p-4 md:p-5 lg:p-6 mb-3 sm:mb-4 md:mb-5 lg:mb-6">
        <div class="flex flex-col space-y-2 xs:space-y-3 sm:space-y-0 sm:flex-row sm:justify-between sm:items-start md:items-center">
          <div class="w-full sm:w-auto">
            <h2 class="text-sm xs:text-base sm:text-lg md:text-xl lg:text-2xl font-semibold text-gray-900 break-words">
              Routing Offices Dashboard
            </h2>
            <p class="text-xs xs:text-sm sm:text-base text-gray-600 mt-1 break-words">
              Incoming documents received by routing offices
            </p>
          </div>
          <div class="text-left sm:text-right w-full sm:w-auto flex-shrink-0">
            <p class="text-xs xs:text-sm text-gray-600">Generated on: {{ currentDate }}</p>
            <p class="text-xs xs:text-sm text-gray-600">Generated by: Kenneth Sayan</p>
          </div>
        </div>
      </div>

      <!-- Mobile Cards (xs to lg) -->
      <div class="block xl:hidden">
        <div class="grid grid-cols-1 gap-2 xs:gap-3 sm:gap-4">
          <div
            v-for="(office, index) in filteredOffices"
            :key="office"
            class="bg-white rounded-md sm:rounded-lg shadow-sm border p-2 xs:p-3 sm:p-4"
          >
            <div class="flex flex-col xs:flex-row xs:items-center xs:justify-between mb-2 pb-2 border-b">
              <h3 class="text-xs xs:text-sm sm:text-base md:text-lg font-semibold text-gray-900 break-words mb-1 xs:mb-0">
                {{ office }}
              </h3>
              <span class="text-xs xs:text-sm sm:text-base font-bold text-gray-700 whitespace-nowrap">
                Total: {{ getOfficeTotal(office) }}
              </span>
            </div>
            <div class="grid grid-cols-2 xs:grid-cols-3 sm:grid-cols-4 md:grid-cols-6 lg:grid-cols-8 gap-1 xs:gap-2 sm:gap-3 text-xs xs:text-sm">
              <div
                v-for="(value, monthIndex) in getOfficeData(office)"
                :key="monthIndex"
                class="flex flex-col p-1 xs:p-2 rounded bg-gray-50 hover:bg-blue-50 transition-colors"
              >
                <span class="text-xs font-medium text-gray-500 text-center break-words">
                  {{ visibleMonths[monthIndex] }}
                </span>
                <span class="font-medium text-gray-900 text-center">{{ value }}</span>
              </div>
            </div>
          </div>
        </div>
      </div>

      <!-- Desktop Table (xl and up) -->
      <div class="hidden xl:block bg-white rounded-lg shadow-sm border overflow-hidden flex-1">
        <div class="overflow-x-auto">
          <div class="inline-block min-w-full align-middle">
            <div class="overflow-hidden">
              <table class="min-w-full table-fixed divide-y divide-gray-200">
                <thead class="bg-gray-50">
                  <tr>
                    <th class="sticky left-0 z-20 bg-gray-50 p-2 sm:p-3 text-left text-xs sm:text-sm font-medium text-gray-500 uppercase tracking-wider min-w-[120px] sm:min-w-[150px]">
                      Routing Offices
                    </th>
                    <th 
                      v-for="month in visibleMonths" 
                      :key="month"
                      class="p-2 sm:p-3 text-center text-xs sm:text-sm font-medium text-gray-500 uppercase tracking-wider min-w-[60px] sm:min-w-[80px]"
                    >
                      {{ month }}
                    </th>
                    <th class="p-2 sm:p-3 text-center text-xs sm:text-sm font-medium text-gray-500 uppercase tracking-wider bg-blue-50 min-w-[80px] sm:min-w-[100px]">
                      Total
                    </th>
                  </tr>
                </thead>
                <tbody class="bg-white divide-y divide-gray-200">
                  <tr 
                    v-for="(office, index) in filteredOffices" 
                    :key="office"
                    :class="[index % 2 === 0 ? 'hover:bg-gray-50' : 'bg-gray-50']"
                  >
                    <td 
                      class="sticky left-0 z-10 p-2 sm:p-3 text-xs sm:text-sm font-medium text-gray-900 break-words"
                      :class="index % 2 === 0 ? 'hover:bg-gray-50' : 'bg-gray-50'"
                    >
                      {{ office }}
                    </td>
                    <td 
                      v-for="(value, monthIndex) in getOfficeData(office)"
                      :key="monthIndex"
                      class="p-2 sm:p-3 text-xs sm:text-sm text-gray-900 text-center whitespace-nowrap"
                    >
                      {{ value }}
                    </td>
                    <td class="p-2 sm:p-3 text-xs sm:text-sm font-semibold text-gray-900 text-center whitespace-nowrap bg-blue-50">
                      {{ getOfficeTotal(office) }}
                    </td>
                  </tr>
                </tbody>
                <tfoot class="bg-gray-100">
                  <tr>
                    <td class="sticky left-0 z-10 bg-gray-100 p-2 sm:p-3 text-xs sm:text-sm font-bold text-gray-900 whitespace-nowrap">
                      TOTAL
                    </td>
                    <td 
                      v-for="(total, index) in monthlyTotals"
                      :key="index"
                      class="p-2 sm:p-3 text-xs sm:text-sm font-bold text-gray-900 text-center whitespace-nowrap"
                    >
                      {{ total }}
                    </td>
                    <td class="p-2 sm:p-3 text-xs sm:text-sm font-bold text-gray-900 text-center whitespace-nowrap bg-blue-100">
                      {{ grandTotal }}
                    </td>
                  </tr>
                </tfoot>
              </table>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</template>